= Resultados y conclusiones

== Conocimientos adquiridos

Gracias al estudio de las metodologías de Pentesting hemos podido no sólo adquirir habilidades en el desarrollo de una auditoría de seguridad, sino que también hemos desarrollado una metodología propia de pentesting que contempla lo que hemos valorado, con las partes esenciales que tiene el desarrollo de un pentest.

Las conclusiones a las que hemos podido llegar una vez realizado el estudio de las metodologías son los siguientes:

* Las metodologías tienen un orden secuencial de fases que se han de seguir y que el éxito de la fase en la que nos encontremos dependerá del trabajo realizado en la fase anterior.
* Hay que dejar bien claro en la fase de _Determinar el alcance y los objetivos del pentest_ qué deseamos cubrir y que estos objetivos han de ser plasmados y firmados por la empresa contratante y por la que presta los servicio de auditoría de seguridad.
* La etapa de descubrimiento nos va a proporcionar la información necesaria para realizar las pruebas con éxito, ya que en ella se realiza un análisis de los activos de la empresa, recopilando información de los riesgos y amenazas que puede sufrir, así como de las vulnerabilidades que estos tienen.
* Durante la etapa de ejecución hemos de ser precavidos para no ser descubiertos por el equipo defensivo de la empresa (_Blue Team_).
* Es necesario realizar un informe donde se documente y se resuma el trabajo realizado, los resultados obtenidos y las recomendaciones que nos proporcionarán información para resolver las vulnerabilidades encontradas.
* Es importante desarrollar software seguro e instalarlo en entornos igual de seguros.
* Los sistemas informáticos tienen que estar actualizados para reducir el impacto de las posibles amenazas.
* La integración continua es vital para que los sistemas informáticos no se queden obsoletos e inseguros.
* Existen herramientas y distribuciones exclusivas para la realización de auditorías de seguridad.

== Dificultades encontradas

Las mayores dificultades a la hora de realizar el estudio han sido las siguientes:

* Crear una máquina vulnerable Windows: al tratarse de software propietario, que requiere una licencia para su uso y que Microsoft no proporciona acceso a las _ISO_'s de sus sistemas operativos, anteriores a Windows 8.1, lo que complica poder crear y publicar legalmente la máquina virtual.
* La versión dockerizada de Metasploitable2, no dispone de soporte completo para todos y cada uno de sus servicios, uno de ellos es el de NFS, que para poder llevar a cabo el pentest de demostración, hemos tenido que hacer uso de la versión original de Metasploitable2, la máquina virtual _.ova_.

== Líneas de trabajo futuro

Se pueden considerar las siguientes líneas de trabajo futuras:

* Automatización de la metodología e implementarla en un entorno SecDevOps a la hora de realizar los tests de intrusión.
* Creación de aplicación web para mostrar resultados y estadísticas del pentest.
* Demostración de un ataque sobre una máquina Windows.
