= Introducción

== Ciberseguridad y SI

La ciberseguridad es un elemento indispensable en un mundo que tiende a estar cada vez más conectado, lo cual lleva implícito un auge de ciberataques.

Los ataques de tipo cibernético se han consolidado como uno de los mayores riesgos a los que está expuesta una empresa. Esto se debe a que el mundo de las TICs evoluciona y cambia contínuamente, por lo que es importante entender cómo proteger los Sistemas de información (SI) y activos informáticos de las empresas públicas y privadas <<bib2>>.

Las pruebas de penetración (o pentesting), nacieron de la necesidad de protegernos de estos ataques. Estas son llevadas a cabo por equipos (propios o ajenos a la empresa) especializados en detectar posibles vías de entrada a los SI, antes de que puedan ser detectadas y explotadas por un ciberdelincuente <<bib3>>.

El responsable de realizar estas pruebas de penetración es el pentester o Hacker Ético <<bib4>>. El Hacker Ético es un profesional en el campo de la ciberseguridad encargado de encontrar fallos en los SI de las corporaciones para que puedan ser solucionados lo antes posible y evitar un ataque informático.

Con el presente trabajo queremos analizar las distintas metodologías de pentesting para que el pentester o Hacker Ético pueda utilizarlas según sus necesidades.

== Motivación

Nuestra pasión por el hacking ético, se ve reflejada en nuestro día a día, desde la primera hasta la última línea de código que escribimos; procurando siempre mantener unas buenas prácticas dentro y fuera del trabajo; asistiendo a conferencias siempre que nos es posible; y realizando CTFs para pasar el tiempo.

Nuestro afán por conocer en mayor profundidad las metodologías, técnicas y herramientas que se utilizan en pentesting, nos ha llevado a realizar éste PFM, esperando que pueda convertirse en una guía útil tanto para los profesionales del sector como para aquellos que acaban de introducirse en él.

No lo dudamos ni un segundo para unir esfuerzos, Sergi y Jansu, en cuanto se nos presentó la oportunidad de realizar éste proyecto, propuesto por Chema Alonso y tutorizado por Pablo González, dos de los máximos referentes en materia de ciberseguridad de nuestro país, cuya trayectoria llevamos siguiendo desde nuestras primeras tomas de contacto con esta rama de la tecnología.

== Objetivos

=== Objetivo general

Analizar las principales metodologías de pentesting que existen, comprendiendo las principales fortalezas de cada una de ellas y en qué escenarios es más conveniente aplicar unas u otras.

=== Objetivos específicos

Establecemos los siguientes objetivos específicos:

* Generar una metodología de aprendizaje básico en pentesting, que sirva de soporte para aquel que quiera introducirse en el ámbito.
* Conocer las fases más comunes del pentesting y aplicarlas de manera práctica sobre algunas de las aplicaciones vulnerables de entrenamiento más conocidas.
* Realizar un análisis comparativo de las distintas metodologías de pentesting.
* Conocer las herramientas más comunes que se utilizan en cada fase.
* Desplegar un laboratorio versátil para poder poner en práctica lo aprendido y que sea apto para su uso en un escenario real.
