= Informe Ejecutivo

Un informe ejecutivo de una auditoría de seguridad debería constar de los siguientes apartados:

* Portada
* Introducción
* Resumen ejecutivo
* Alcance de la auditoría
* Hallazgos
* Conclusiones

A continuación, se describen algunos de los puntos anteriores para nuestro caso de estudio.

== Introducción

El objeto de la auditoría es determinar el nivel de seguridad de un servidor Linux y dos aplicaciones web. La metodología empleada será Aika, que se compone de cuatro fases: Determinar el alcance y los objetivos del pentest; Descubrimiento; Ejecución; y por último, Informes, limpiezas y destrucción de la información. Los miembros del equipo que realizaran la metodología son Jansu Soria (aka Asori-han) y Sergi Milla (aka Kuerubo).

== Resumen ejecutivo

Durante la auditoría de seguridad se ha detectado que el servidor Linux consta de un total de 24 servicios vulnerables y que las aplicaciones web tienen un total de 8 vulnerabilidades críticas que podrían comprometer a la empresa produciendo fugas de información y poniendo los sistemas en peligro.

== Alcance de la auditoría

La auditoría se llevará a cabo en una red empresarial que consta de un total de cuatro máquinas, donde se insertarán dos máquinas atacantes que, realizarán un escaneo de todo el sistema informático.

== Hallazgos

Durante la auditoría de seguridad, se han encontrado los siguientes servicios vulnerables en el servidor:

[source]
----
PORT     STATE SERVICE     REASON  VERSION
21/tcp   open  ftp         syn-ack vsftpd 2.3.4
22/tcp   open  ssh         syn-ack OpenSSH 4.7p1 Debian 8ubuntu1 (protocol 2.0)
23/tcp   open  telnet      syn-ack Linux telnetd
25/tcp   open  smtp        syn-ack Postfix smtpd
53/tcp   open  domain      syn-ack ISC BIND 9.4.2
80/tcp   open  http        syn-ack Apache httpd 2.2.8 ((Ubuntu) DAV/2)
111/tcp  open  rpcbind     syn-ack 2 (RPC #100000)
139/tcp  open  netbios-ssn syn-ack Samba smbd 3.X - 4.X (workgroup: WORKGROUP)
445/tcp  open  netbios-ssn syn-ack Samba smbd 3.X - 4.X (workgroup: WORKGROUP)
512/tcp  open  exec        syn-ack netkit-rsh rexecd
513/tcp  open  login       syn-ack
514/tcp  open  tcpwrapped  syn-ack
1099/tcp open  java-rmi    syn-ack GNU Classpath grmiregistry
1524/tcp open  bindshell   syn-ack Metasploitable root shell
2049/tcp open  nfs         syn-ack 2-4 (RPC #100003)
2121/tcp open  ftp         syn-ack ProFTPD 1.3.1
3306/tcp open  mysql       syn-ack MySQL 5.0.51a-3ubuntu5
5432/tcp open  postgresql  syn-ack PostgreSQL DB 8.3.0 - 8.3.7
5900/tcp open  vnc         syn-ack VNC (protocol 3.3)
6000/tcp open  X11         syn-ack (access denied)
6667/tcp open  irc         syn-ack UnrealIRCd
8009/tcp open  ajp13       syn-ack Apache Jserv (Protocol v1.3)
8180/tcp open  http        syn-ack Apache Tomcat/Coyote JSP engine 1.1
Service Info: Hosts:  metasploitable.localdomain, irc.Metasploitable.LAN; OSs: Unix, Linux; CPE: cpe:/o:linux:linux_kernel
----

Y las siguientes vulnerabilidades en las aplicaciones web:

* SQL Injection
* SQL Injection (Blind)
* Command Injection
* XSS (Reflected)
* XSS (Stored)
* CSRF
* Brute Force
* Weak Session IDs

== Conclusiones

Tras el análisis sobre la red empresarial, se constata que el servidor Linux consta de varios servicios vulnerables que un atacante podría aporvechar para acceder al sistema, la mayoria de estas vulnerabilidades se podrían solventar actualizando el sistema operativo y sus servicios, aplicando los parches de seguridad más recientes.

En lo que respecta a las aplicaciones web analizadas, se recomienda encarecidamente replantear completamente la arquitectura de las mismas, siguiendo las guías de buenas prácticas para el desarrollo seguro de software.
