= Estado del Arte

Para entender el contexto en el que se desarrolla la actividad del pentesting habría que retroceder a los años 60 <<bib1>>, cuando los expertos informáticos comienzan a darse cuenta de que existe la posibilidad de acceder a los sistemas informáticos sin autorización, es en ese momento cuando se diseñan las primeras pruebas para comprobar la seguridad de estos. Estas pruebas son lo que hoy conocemos como auditoría de seguridad o pentesting, las cuales fueron evolucionando a la vez que la tecnología avanzaba.

En los años 70 y con el origen de ARPANET, que permite conectar ordenadores entre ellos a largas distancias, se asientan las bases de la ciberseguridad, ya que aparece el primer malware, un virus informático. _Creeper_ fue uno de ellos, un simple programa que pivotava de un ordenador a otro, siempre que estuviera conectado a ARPANET. Para mitigar _Creeper_, surgió _Reaper_, primer software de seguridad o antivirus, impulsando la carrera entre el desarrollo de malware y antimalware.

Además de la propagación de virus, ARPANET originó riesgos de robo de información, ya que los ordenadores conectados no disponían de sistemas de seguridad para intursiones, solamente una contraseña para acceder al sistema.

Este hecho, motivó el lanzamiento de un nuevo ARPANET para analizar la protección de los sistemas y dar soluciones a los riesgos de seguridad. En este proyecto participaron grandes empresas y el gobierno estadounidense. Sin embargo, a pesar de aumentar la seguridad, surgió un nuevo tipo de ataque, conocido como ingeniería social, el cual se aprovecha del error humano. Los ataques basados en ingeniería social, siguen siendo ampliamente utilizados en la actualidad.

Es en 1970 cuando empiezan a cifrarse los datos con el algoritmo _Data Encryption Standard_ (DES), inventado por IBM, entendiendo que no sólo los sistemas tienen que protegerse, sino que los datos contenidos en estos también deben ser cifrados. En 1977, promovido por la NSA, DES se convirtió en un estándar, el cual se continuó utilizando hasta 2001.

En 1980, la ciberseguridad se extiende a los ordenadores de la administración pública, instituciones financieras y muchos más ámbitos en los que estos se conectan a internet. El aumento exponencial de la superficie de exposición, se traduce en un gran número de oportunidades para que los ciberdelincuentes traten de robar o manipular la información de los sistemas informáticos mediante el uso de malware, provocando grandes pérdidas económicas. 

Es a partir del 2000, con la proliferación de internet, tanto en el ámbito doméstico como en el comercial, cuando la ciberdelincuencia evoluciona con un desarrollo de malware más especializado, enviado a través del correo electrónico.

Tal y como podemos ver, el malware y los riesgos a los que están expuestos los sistemas de información, evolucionan a medida que lo hacen estos últimos, lo que implica el estudio constante de vulnerabilidades y el desarrollo de contramedidas, a partir de auditorías de seguridad, conocidas como pentests.

== ¿Qué es el pentesting?

Un pentesting es un conjunto de ataques simulados, dirigidos a un sistema informático con una única finalidad: detectar posibles debilidades o vulnerabilidades para que sean corregidas y no puedan ser explotadas. Estas auditorías comienzan con la recogida, en fuentes de acceso abierto —Open Sources Intelligence (OSINT)—, de información sobre la empresa, los empleados, usuarios, sistemas y equipamientos.

Continúan con un análisis de vulnerabilidades, que se intentarán explotar, incluso con técnicas de ingeniería social, atacando a los sistemas hasta conseguir sus objetivos.

Finalmente, se realiza un informe a partir de los datos obtenidos, incluyendo los obtenidos en la fase de recogida, y en el que se detallan las vulnerabilidades descubiertas, aquellas que se han conseguido explotar o que podrían explotarse, el grado de criticidad, reproducibilidad, etc.

En la preparación del pentest, se realiza un plan con un conjunto de ataques dirigidos, según la tecnología que se utilice en la empresa y sus necesidades de seguridad. Para ello, los auditores cuentan con metodologías —algunas específicas según la tecnología o estándares de seguridad que se deseen implantar, y otras más generales—, que les ayudan a realizarlas de forma sistemática. En el alcance del pentest, se acuerda con la empresa qué pruebas se realizarán y sobre qué aplicaciones o servicios.

Es decir, el pentester juega el rol de ciberdelincuente, bajo las condiciones establecidas en el alcance del pentest, simulando ataques tal y como los llevaría a cabo un verdadero ciberdelincuente que quisiera hacerse con el control del sistema o con la información en él contenida.

De esta forma, se puede determinar:

* Si el sistema informático es vulnerable o no.
* Evaluar si las defensas con las que cuenta, son suficientes y eficaces.
* Valorar la repercusión de los fallos de seguridad que se detecten.

== Tipos de pentest

Existen tres tipos de pentest, dependiendo de la información de los sistemas informáticos que se van a testar, los cuales, son:

=== Caja negra

También conocido como _Black Box Pentesting_, en este caso el pentester hace las pruebas a ciegas, es decir, sin tener ningún tipo de información del sistema informático o la aplicación que tiene que evaluar. Este tipo de prueba es lo más similar a un ciberataque que pueda sufrir una empresa.

=== Caja blanca

También conocido como _White Box Pentesting_, a diferencia del caso anterior, el pentester dispone de toda la información del sistema a evaluar: contraseñas, firewalls, IPs, código fuente, etc. Esta prueba es la más completa a la que puede someterse un objetivo y con el que se pueden mejorar las defensas de éste.

=== Caja gris

También conocido como _Grey Box Pentesting_, que mezcla de los dos conceptos anteriores. El pentester dispone de información previa a la ejecución del pentest, pero parcial.

== Fases del pentest

El pentester realiza, esencialmente, las siguientes fases para una auditoría, con ciertos matices, según la metodología escogida:

. Planificación
. Recopilación
. Análisis de vulnerabilidades
. Modelado de amenazas
. Explotación del sistema
. Elaboración de informes

Cabe destacar que para que una auditoría tenga sentido, estas fases deben tratarse como un proceso cíclico, sirviendo los informes elaborados para reforzar los sistemas de seguridad y auditarlos nuevamente.

=== Planificación 

Es esta primera fase se definen los objetivos del pentest: sistemas y servicios que se van a abordar, hora en la que se va a abordar y métodos que se emplearan para hacerlo y el entorno en el que se realizarán las pruebas (producción, preproducción, desarrollo, etc.).

=== Recolección

Consiste en recoger los datos que sea posible obtener y que puedan contribuir en la ejecución de los tests de penetración. Algunos datos que puede ser interesante obtener son:

* Información de red (normalmente obtenida mediante escaneos de IP, dominios o puertos).
* Información sobre versiones de los sistemas operativos y de los servicios.
* Obtención de metadatos.
* Aplicar dorking (hacking con motores de búsqueda).
* Realizar técnicas de scraping.

Este tipo de recolección puede ser pasiva, en la que nunca se enviará tráfico directamente al objetivo, sino que se "escuchará" y analizará el tráfico que sea posible, tratando de evitar posibles IDS's (sistemas de detección de intrusos), o bien puede ser activa, donde es posible que seamos detectados por dichos IDS's, ya que se puede inyectar tráfico sospechoso o malicioso. El envío de un _ping_ se considera una prueba activa y permite saber si un host se encuentra levantado en la red o no, algunos sistemas como Windows, desactivan la respuesta a ping por defecto, como medida de seguridad.

Algunos IDS's más sofisticados, implementan inteligencia artificial para detectar tráfico anómalo en la red.

=== Análisis de vulnerabilidades

En esta fase, se tratan de identificar las vulnerabilidades de los objetivos: sensibilidad a inyecciones de código; uso de una versión vulnerable de algún servicio (se puede consultar una base de datos como https://www.exploit-db.com[Exploit Database]); ausencia de filtros para prevenir ataques DoS (denegación de servicio); éxito en técnicas de ingeniería social enviando mensajes de phishing a empleados; etc.

=== Modelado de amenazas

Se define la estrategia a seguir durante el ataque en la fase de explotación.

=== Explotación del sistema

Se llevan a cabo los ataques sobre los objetivos, para evaluar las amenazas y llevar al límite las defensas del sistema. Aquí se contrasta el verdadero estado de seguridad de los objetivos.

=== Redacción de informes

Finalmente, se elaboran los informes que sean precisos para informar al cliente del estado de seguridad de los sistemas y aplicaciones auditados, pruebas a las que han sido sometidos y el resultado de las mismas, conclusiones, medidas correctivas y análisis del balance entre el coste y el beneficio de aplicarlas.

== Herramientas utilizadas en el pentesting

Para cada fase del pentest, existen numerosas aplicaciones, como pueden ser Nmap, Dnsrecon, The Harvester para la etapa de recolección de información; Burpsuite y Nessus para detectar puntos débiles; Metasploit Framework para elaborar exploits y medir el alcance de las vulnerabilidades una vez detectadas, pudiendo explotarlas; John the Ripper para descifrar contraseñas y romper hashes; o Veil, para enmascarar código malicioso.

Muchas de estas herramientas pueden ser utilizadas y automatizadas mediante Python, un lenguaje flexible, potente y fácil de aprender, que puede facilitar el proceso. Para profundizar en el uso de herramientas de pentest mediante Python, se recomienda la lectura del libro _Python para Pentesters_, de Daniel Echeverri (aka Adastra), publicado por 0xWord.
