version: '3.9'
services:
  attacker1:
    build: ./kali
    hostname: kali
    privileged: true
    networks:
      pentest:
      vulnerable:
        ipv4_address: ${ATTACKER1_IP}
    tty: true
    profiles:
      - kali-attacker
    environment:
      - XAUTHORITY=/root/.Xauthority
      - DISPLAY=${HOST_IP}:0
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${DOCKER_LAB_DIR}/workspace:/root/workspace
    extends:
      file: ports.yaml
      service: kali-ports
  attacker2:
    build: ./parrot
    hostname: parrot
    privileged: true
    networks:
      pentest:
      vulnerable:
        ipv4_address: ${ATTACKER2_IP}
    tty: true
    profiles:
      - parrot-attacker
    environment:
      - XAUTHORITY=/root/.Xauthority
      - DISPLAY=${HOST_IP}:0
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${DOCKER_LAB_DIR}/workspace:/root/workspace
    extends:
      file: ports.yaml
      service: parrot-ports
  vulnerable1:
    build: ./metasploitable2
    hostname: metasploitable
    networks:
      vulnerable:
        ipv4_address: ${VULNERABLE1_IP}
    tty: true
    profiles:
      - vulnerable
  vulnerable2:
    image: webgoat/goatandwolf
    hostname: webgoat
    networks:
      vulnerable:
        ipv4_address: ${VULNERABLE2_IP}
    tty: true
    profiles:
      - vulnerable
  vulnerable3:
    image: bkimminich/juice-shop
    hostname: juice-shop
    networks:
      vulnerable:
        ipv4_address: ${VULNERABLE3_IP}
    tty: true
    profiles:
      - vulnerable
  vulnerable4:
    image: vulnerables/web-dvwa
    hostname: dvwa
    networks:
      vulnerable:
        ipv4_address: ${VULNERABLE4_IP}
    tty: true
    profiles:
      - vulnerable
  adocrenderer:
    build: ./asciidoctor
    hostname: asciidoctor
    volumes:
      - ${REPO_DIR}:/documents/
    tty: true
    entrypoint: "/bin/bash"
    profiles:
      - documentation
networks:
  vulnerable:
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: ${VULNERABLE_NETWORK}
          gateway: ${GW_IP}
  pentest:
    driver: bridge
