= Comparativa entre metodologías

Tras examinar cada una de las metodologías, cabe destacar que tienen muchos puntos en común entre ellas, siendo la PTES la que tiene más en común con cada una de las demás y la Octopus las más completa. Elegir entre una de ellas depende de varios factores, como el alcance del proyecto, los conocimientos de los miembros del equipo, medios económicos de los que se disponga, la complejidad de la red, el sistema informático a evaluar, etc... 

En la siguiente figura, se muestra un esquema-resumen a fin de poder comparar las diferentes fases de cada una cómodamente.

.Fases de las diferentes metodologías 
[plantuml, format=svg]
----
include::../puml/com_test.puml[]
----

Como podemos observar, la metodología OWASP esta más orientada a pruebas en entornos de aplicaciones web; ISSAF está orientada a la evaluación de los procesos de seguridad, obteniendo una visión global de las vulnerabilidades existentes en el sistema informático; PTES nos proporciona un framework estandarizado de trabajo para la realización de un pentest de forma ordenada; NIST proporciona un proceso general para llevar a cabo una prueba de intrusión cubriendo todos los aspectos informáticos y humanos que tienen contacto con la información de las empresas; OSSTMM toma como base las políticas de seguridad añadiendo controles de seguridad y la indemnización de los activos, cosa que otras metodologías no contemplan.
