= Information Systems Security Assessment Framework (ISSAF)

Esta metodología fue creada por el Open Information Systems Security Group (OISSG) e implementa controles de IEC/ISO 27001, Sarbanes Oxley SOX404, CoBIT, SAS70 y COSO.

Se trata de una metodología muy exhaustiva, lo que hace que sea uno de los frameworks más interesantes dentro del ámbito del pentesting. Esta metodología se encuentra organizada por criterios de evaluación, los cuales, han sido revisados por profesionales de cada una de las áreas de control. Estos criterios son los siguientes:

* Descripción del criterio de evaluación.
* Puntos y objetivos a cubrir.
* Prerrequisitos para conducir la evaluación.
* El propio proceso de evaluación.
* Informe de resultados esperados.
* Contramedidas y recomendaciones.
* Referencias y documentación externa.

Tal y como se puede apreciar en la siguiente imagen, esta metodología consta de tres fases: planificación y preparación; evaluación; informes, limpieza y destrucción de información.

.Metodologia ISSAF 
[plantuml, format=svg]
----
include::../puml/issaf_test.puml[]
----

.Fase I: Planificación y prepación.
En esta fase se firma un documento con un acuerdo de evaluación, que sirve de protección legal para ambas partes. Durante esta fase se proceden a realizar las siguientes actividades:

* Identificación de las personas de contacto de ambas organizaciones.
* Reunión inicial para confirmar el alcance, el enfoque y la metodología.
* Aceptación de casos de pruebas especificos y caminos de escalada de privilegios.

.Fase II: Evaluación
Esta fase presenta un enfoque por capas: cada una de ellas representa un mayor nivel de acceso a los activos de información. Las capas son las siguientes:

. Recopilación de información.
. Mapeo de redes.
. Identificación de vulnerabilidades.
. Penetración.
. Obtención de acceso y escalada privilegios.
. Enumerando.
. comprometer usuarios y sitios remotos.
. Mantener el acceso.
. Ocultar pistas.

.Fase III: Informes, limpieza y destrucción de la información

Una vez realizadas todas las pruebas definidas en el alcance del proyecto de pentesting, se debe generar una memoria que describirá los resultados de las pruebas y las recomendaciones para mejorar la seguridad. Esta memoria deberá reflejar siguientes puntos:

* Resumen de gestión.
* Alcance del proyecto.
* Herramientas utilizadas (incluyendo exploits).
* Fecha y hora reales en las que se llevaron a cabo las pruebas en el sistema.
* Todas y cada una de las salida de las pruebas realizadas (con exclusión de los informes de análisis de vulnerabilidad que pueden ser incluidos como documentos adjuntos).

Si se encontrara una vulnerabilidad crítica durante las pruebas, se debe informar de inmediato. Durante esta fase, toda la información creada en los sistemas de prueba, se eliminará.

.Características clave y beneficios
* ISSAF ofrece una propuesta de alto valor para asegurar la infraestructura mediante la evaluación de los controles de seguridad existentes contra vulnerabilidades críticas.
* Aborda diferentes áreas clave de la seguridad de la información. Estos incluyen la evaluación de riesgos, la estructura y gestión empresarial, la evaluación de controles, la gestión del compromiso, el desarrollo de políticas de seguridad y las mejores prácticas generales.
* Examina la seguridad de una red, sistema o aplicación. El marco puede centrarse de forma transparente en una tecnología específica de objetivos que puede incluir: routers; conmutadores; firewalls; sistemas de detección y prevención de intrusos; redes de área de almacenamiento; redes privadas virtuales; diversos sistemas operativos; servidores de aplicaciones web; bases de datos; etc.
* Elimina la brecha entre la visión técnica y de gestión de las pruebas de seguridad, mediante la implementación de los controles necesarios para manejar ambas áreas.
* Permite a la administración entender los riesgos existentes que flotan sobre las defensas perimetrales de una organización y las reduce de manera proactiva, identificando las vulnerabilidades que pueden afectar a la integridad del negocio.
