= NIST SP 800-115

NIST es el Instituto de Estándares y Tecnología estadounidense, dedicado a desarrollar recursos y organizar programas de formación en múltiples áreas. Las guías NIST y sus frameworks se han convertido en estándares globales en el ámbito de la seguridad del software y hardware que sirven de ayuda a empresas y pentesters.

Estas guías también aportan conjuntos de buenas prácticas en multitud de ámbitos de la ciberseguridad.

La guía NIST SP 800-115 ofrece una base metodológica para diseñar y poner en marcha servicios de pentesting o test de intrusión avanzados. La metodología plantea cuatro fases: planificación, descubrimiento, ejecución del ataque y presentación de informes.

.Metodología NIST SP 800-115 
[plantuml, format=svg]
----
include::../puml/nist_test.puml[]
----

.Planificación
Se establecen los objetivos y las pautas técnicas para que la prueba de pentest tenga éxito.

.Descubrimiento
Se recopila la información necesaria del sistema para el descubrimiento de vulnerabilidades.

.Ejecución
Es la fase clave del proceso, en ella se realiza ataque llevando a cabo las siguientes pruebas:

* Obtención de acceso
* Escalada de privilegios
* Pivotaje entre sistemas
* Instalación de herramientas

A rasgos generales, las vulnerabilidades más explotadas son las siguientes:

* Configuraciones erróneas.
* Fallos en el kernel.
* Desbordamiento de búfer.
* Validación de entrada insuficiente.
* Enlaces simbólicos.
* Ataques a descriptores de archivos.
* Condiciones de carrera.
* Permisos incorrectos de archivos y directorios.

.Presentación de informes
Por último, se redacta el informe donde se describen las vulnerabilidades identificadas, el nivel de riesgo asociado y la propuesta para mitigarlas.
