= Open Web Application Security Project (OWASP)

La guía de pruebas de OWASP es una metodología que describe los 10 riesgos más importantes de las aplicaciones web.

Esta metodología se divide en dos etapas: pasiva y activa.

La etapa pasiva consiste en la recopilación de información para comprender la lógica de la aplicación.

Una vez entendida la lógica, se procede con a la etapa activa, donde se realizan las siguientes pruebas, en orden secuencial:

.Orden secuencial de pruebas en OWASP 
[plantuml, format=svg]
----
include::../puml/owasp_tests.puml[]
----

En cada una de estas pruebas, se realizan las siguientes actividades:

.Recopilación de la información

* Pruebas de firma digital de Aplicaciones Web
* Descubrimiento de aplicaciones
* Técnicas de spidering y googling
* Análisis de códigos de error
* Pruebas de gestión de configuración de la infraestructura
* Pruebas del receptor de escucha de la BBDD
* Pruebas de la gestión de configuración de la aplicación
* Pruebas de manejo de extensión de archivos
* Archivos antiguos, sin referencias y copias de seguridad

.Comprobación de la lógica de negocio

* Reglas de negocio: políticas del negocio
* Flujos de trabajo: tareas ordenadas de paso de documentos o datos de un elemento participante a otro

.Pruebas de autenticación

* Pruebas de diccionario sobre cuentas de usuario o cuentas por defecto
* Fuerza bruta
* Saltarse el sistema de autenticación
* Atravesar directorios/acceder a archivos adjuntos externos
* Sistemas de recordatorio/reset de contraseñas vulnerables

.Pruebas de gestión de sesiones

* Pruebas de gestión del caché de navegación y de salida de sesión
* Análisis del esquema de gestión de sesiones
* Manipulación de cookies y testigos de sesión
* Variables de sesión expuestas
* Abuso de sesión
* Exploit HTTP
* Pruebas de CSRF (Cross Site Request Forgery)
* Cross Site Scripting
* Métodos HTTP y XST

.Pruebas de validación de datos

* Inyección SQL
* Inyección LDAP
* Inyección ORM
* Inyección XML
* Inyección SSI
* Inyección Xpath
* Inyección IMAP/SMTP
* Inyección de código
* Inserción de comandos del sistema operativo
* Prueba de desbordamiento de búfer
* Pruebas de vulnerabilidad incubada
* Bloqueo de cuentas de usuario

.Pruebas de denegación de servicio

* Desbordamiento de búfer
* Reserva de objetos especificada por usuarios
* Pruebas de uso de entradas de usuario como bucle
* Pruebas de escritura de entradas suministradas por usuario a disco
* Fallos en la liberación de recursos
* Pruebas de almacenamiento excesivo en la sesión

.Comprobación de servicios web

* Pruebas estructurales de XML
* Comprobación de XML a nivel de contenido
* Comprobación de parámetros HTTP GET/REST (Representational State Transfer)
* Adjuntos SOAP maliciosos
* Pruebas de repetición

.Pruebas de AJAX

* Inyección SQL
* Cross Site Scripting
* Explotación de XSS
* Inyección DOM (Modelo de Objeto de Documentos)
* Inyecciones JSON/XML/XSLT
* Cross Site Request Forgery (CSRF)
* Denegación de Servicio

== Características clave y beneficios

* La prueba de las aplicaciones web frente a los 10 principales riesgos de seguridad de OWASP asegura que se evitan los ataques y debilidades más comunes y se mantiene la confidencialidad, integridad y disponibilidad de una aplicación.

* La comunidad OWASP ha desarrollado una serie de herramientas de seguridad que se centran en las pruebas de aplicaciones web automatizadas y manuales. Algunas de estas herramientas son WebScarab, Wapiti, JBroFuzz y SQLiX, que también están disponibles bajo el sistema operativo Kali Linux.

* Al considerar la evaluación de la seguridad de la infraestructura web, la Guía de Pruebas de OWASP proporciona detalles de evaluación específicos de cada tecnología; por ejemplo, la prueba de Oracle se aborda de forma diferente a la de MySQL. Dicha guía proporciona una visión más amplia, abarcando múltiples tecnologías, lo que ayuda al auditor a elegir el procedimiento más adecuado para las pruebas.

* Invita a los desarrolladores a llevar a cabo las prácticas de codificación segura mediante la integración de pruebas de seguridad en cada etapa del desarrollo, lo cual dotará a la aplicación de mayor robustez, seguridad y prevendrá posibles errores en producción.

* Proporciona aceptación y visibilidad en toda la industria. Los diez principales riesgos de seguridad también pueden alinearse con otros estándares de evaluación de seguridad de aplicaciones web, lo que permite el cumplimiento de varios estándares sin que suponga un aumento considerable de esfuerzos.
