= Metodologías de pentesting

La ciberseguridad es un elemento indispensable en un mundo que tiende a estar cada vez más conectado, lo cual lleva implícito un auge de ciberataques.

Los ataques de tipo cibernético se han consolidado como uno de los mayores riesgos a los que está expuesta una empresa. Esto se debe a que el mundo de las TICs evoluciona y cambia continuamente, por lo que es importante entender cómo proteger los Sistemas de información (SI) y activos informáticos de las empresas públicas y privadas.

Las pruebas de penetración (o pentesting), nacieron de la necesidad de protegernos de estos ataques. Estas son llevadas a cabo por equipos (propios o ajenos a la empresa) especializados en detectar posibles vías de entrada a los SI, antes de que puedan ser detectadas y explotadas por un ciberdelincuente.

El responsable de realizar estas pruebas de penetración es el pentester o Hacker Ético. El Hacker Ético es un profesional en el campo de la ciberseguridad encargado de encontrar fallos en los SI de las corporaciones para que puedan ser solucionados lo antes posible y evitar un ataque informático.

Actualmente existen varios tipos de metodologías de Pentesting como OWASP, ISSAF, OSSTMM, PTES, NIST 800-115, OCTOPUS, cabe destacar que tienen muchos puntos en común entre ellas, siendo la PTES la que tiene más en común con cada una de las demás y la OCTOPUS las más completa. Elegir entre una de ellas depende de varios factores, como el alcance del proyecto, los conocimientos de los miembros del equipo, medios económicos de los que se disponga, la complejidad de la red, el sistema informático a evaluar, etc... 

La metodología OWASP esta más orientada a pruebas en entornos de aplicaciones web; ISSAF está orientada a la evaluación de los procesos de seguridad, obteniendo una visión global de las vulnerabilidades existentes en el sistema informático; PTES nos proporciona un framework estandarizado de trabajo para la realización de un pentest de forma ordenada; NIST proporciona un proceso general para llevar a cabo una prueba de intrusión cubriendo todos los aspectos informáticos y humanos que tienen contacto con la información de las empresas; OSSTMM toma como base las políticas de seguridad añadiendo controles de seguridad y la indemnización de los activos, cosa que otras metodologías no contemplan.

.Aika (Asori & Kuerubo)
A partir del estudio de estas metodologías, hemos elaborado una propia: Aika. Partiendo de la premisa que sea sencilla de llevar a cabo por parte de aquellos que están empezando en el ámbito de la ciberseguridad. Se compone de 4 fases:

. Determinar el alcance y los objetivos del pentest: se firma un documento de evaluación que sirve de protección legal para ambas partes.
. Descubrimiento (recopilación de información, mapeo de redes y análisis de vulnerabilidades): se recopila la información suficiente para realizar el ataque.
. Ejecución (Explotación y Post-Explotación): aprovechando las amenazas y vulnerabilidades detectadas, se lanza el ataque.
. Informes, limpieza y destrucción de la información: se genera una memoria que describe los resultados de las pruebas y medidas correctivas y recomendaciones.

.Metodología Aika 
[plantuml, format=svg]
----
include::includes/puml/ak_test.puml[]
----

Como se puede observar, esta metodología aporta una serie de beneficios:

* Orden secuencial claro y sencillo de seguir para alguien que se inicia en el hacking ético.
* Esta formada por los puntos más importantes de la metodologías antes mencionadas.
* Se puede aplicar para cualquier ámbito en el que se quiera hacer un pentest.

Gracias al estudio de las metodologías de Pentesting hemos podido no sólo adquirir habilidades en el desarrollo de una auditoría de seguridad, sino que también hemos desarrollado una metodología propia de pentesting que contempla lo que hemos valorado con las partes esenciales que deberían desarrollarse en un pentest.

Con Aika, cualquier novato en el mundo del pentest podrá realizar una auditoría de seguridad en cuatro pasos ordenados sin dejarse los puntos claves obteniendo obteniendo una visión global de las vulnerabilidades existentes en el sistema informático.

.Laboratorio de pentest
Nuestra propuesta la acompañamos de un laboratorio de pentest desplegado en Docker, consta de dos contenedores de ataque que pueden ser utilizadas al gusto del consumidor (Kali y Parrot) y 4 vulnerables, la versión dockerizada de las archiconocidas: Metasploitable2, DVWA, Web Goat y Juice-shop.

El despliegue de los contenedores se realiza mediante un script de bash que permite seleccionar los contenedores que serán levantados, los puertos que se desean exponer y la configuración de red y compilar la memoria de nuestro proyecto de final de máster, la cual hemos redactado utilizando https://docs.asciidoctor.org/asciidoc/latest/[Asciidoctor].

Además, se han configurado los contenedores para poder lanzar aplicaciones gráficas si disponemos en nuestro host de un servidor X11, lo que permite el uso de herramientas como Burpsuite o Wireshark.

Este laboratorio es apto para su uso en un entorno real de pentest y esperamos que pueda serle de utilidad tanto a los profesionales con mayor experiencia como a los que están empezando su camino en este mundo tan apasionante.

.Demostración del laboratorio
//video::[Laboratorio de pentest]

Enlace el repositorio: https://github.com/Asori-han/pentesting-methodologies[Asori-han/pentesing-methodologies].

Un saludo.

Autores: Sergi Milla y Jansu Soria.
