[quote, Miyamoto Musashi,El Libro de los Cinco Anillos: Libro del viento]
Aunque sean torpes en ellas, los guerreros deben fortalecer personalmente sus propias artes marciales tanto como puedan sus propias circunstancias.

<<<

:sectnums!:
== Agradecimientos
En primer lugar nos gustaría agradecer a Rubén Alonso y a Carlos E. Gómez por el apoyo que nos han prestado en la realización de este trabajo fin de máster, a nuestro tutor Pablo González por la guía ofrecida en la realización del trabajo, y por último agradecer a nuestras familias por su apoyo incondicional, animándonos a seguir siempre adelante.

<<<

== Resumen

El presente proyecto final de máster presenta el estudio realizado de cinco de metodologías de pentesting que han permitido la elaboración teórica y práctica de una nueva metodología de pentesting llamada Aika, orientada al pentester _newbie_, que se compone de cuatro fases, las cuales son: Determinar el alcance y los objetivos del pentest; Descubrimiento, donde se recopila la información suficiente para realizar el ataque; Ejecución, donde se aprovechan los vectores de ataque detectados en la etapa anterior para explotar las vulnerabilidades detectadas y; por último, Informes, limpieza y destrucción de la información, donde se genera una memoria que describe los resultados de las pruebas y medidas correctivas y recomendaciones.

La elaboración práctica de esta nueva metodología se ha realizado en un laboratorio compuesto por dos máquinas atacantes, Kali y Parrot, y cuatro vulnerables, DVWA, WebGoat, Juice-Shop y Metasploitable2, en un entorno de contenedores Docker.

Palabras clave: Metodologías de pentesting, Docker, OSSTMM, PTES, ISSAF, OWASP, NIST.


== Abstract

This final master's project presents the study of five pentesting methodologies that have allowed the theoretical and practical development of a new pentesting methodology called Aika, oriented to the _newbie_ pentester, which is made up of four phases, which are: Determine the scope and objectives of the pentest; Discovery, where enough information is collected to carry out the attack; Execution, where the attack vectors detected in the previous stage are used to exploit the vulnerabilities detected and; Finally, Reports, cleaning and destruction of information, where a report is generated that describes the results of the tests and corrective measures and recommendations.

The practical development of this new methodology has been carried out in a laboratory made up of two attacking machines, Kali and Parrot, and four vulnerable ones, DVWA, WebGoat, Juice-Shop and Metasploitable2, in a Docker container environment.

Keywords: Pentesting methodologies, Docker, OSSTMM, PTES, ISSAF, OWASP, NIST.